### ISSUE TITLE
Error net::ERR_SPDY_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by Merlak** [dunglas/mercure#106] opened 2019-06-21 11:36 UTC
I'm trying to use mercure in GCE kubernetes cluster with existing API platform setup and I've started to get network errors for subscribers every 30 seconds when moved from localhost to cluster.
The error is:

> GET https://mercure.example.com/hub?topic=https%3A%2F%2Fmercure.example.com%2Fhub%2Ftest%2F1 **net::ERR_SPDY_PROTOCOL_ERROR 200**

I'm attaching chrome development tools print screen for better clarification:
![mercure-debug](https://user-images.githubusercontent.com/2973541/59919548-c70b5980-9438-11e9-9a4e-493392988b34.png)

My subscriber html script is:
<script>
const es = new EventSource('https://mercure.example.com/hub?topic=' + encodeURIComponent('https://mercure.example.com/hub/test/1'));
es.onmessage = e => {
    console.log(JSON.parse(e.data));
}
</script>

Otherwise publishing works just fine and subscriber is notified, only the constant network errors remain the problem.

I also set the **heartbeatInterval: 15s** but it doesn't prevent the error.

Another thing to note is that is that we are using gce ingress which forwards subscriber traffic directly to mercure service.

Any help would be appreciated :)

**Comment by dunglas** [comment] 2019-06-21 15:23
I encountered the same error. This problem is caused by GCP load balancers. I also tried with Digital Ocean, AWS, Bluemix and Heroku, and there are no issues with these providers.
The only workaround I've found so far is to not use a GCP Load Balancers (expose the service directly on the internet).

If someone finds a fix for this, please let me know.

**Comment by Merlak** [comment] 2019-06-29 06:50
We managed to solve this by using backendconfig resource for mercure service defining a different timout for gce load balancer backend service:

> apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: mercure-backendconfig
spec:
  timeoutSec: 86400

In service we then used this backend config:

> annotations:
    beta.cloud.google.com/backend-config: '{"default": "mercure-backendconfig"}'

This solved the default 30 second timeout problems.


It would be great if Mercure helm chart would support this in the future so we don't need to define the  configuration with custom files...

**Comment by dunglas** [comment] 2019-06-29 07:00
Thank you very much for investigating, and for fixing this issue! Would you mind opening a PR on the chart to conditionally include this `BackendConfig`? https://github.com/helm/charts/tree/master/stable/mercure

**Comment by Merlak** [comment] 2019-06-29 20:14
Done - https://github.com/helm/charts/pull/15141
If you can, please update the Go code so we'll now be able to override the defaults for new helm values when using the mercure chart dependency.

**Comment by JSmythSSG** [comment] 2019-07-09 13:03
I seem to be getting the same error message every so often. Mecure is being run on AWS lightsail with nginx reverse proxy. We are using cloudflare with performance disabled but still seem to get them.

Any suggestions would be greatly appreciated.
 
![image](https://user-images.githubusercontent.com/47111806/60889990-37e0ad00-a252-11e9-882f-aed7e548f8f9.png)

**Comment by dunglas** [comment] 2019-07-09 13:04
Have you enabled the heartbeat mechanism?

**Comment by JSmythSSG** [comment] 2019-07-09 13:06
> Have you enabled the heartbeat mechanism?

Heartbeat is set to the default of 15s, should I disable or increase it?

**Comment by dunglas** [comment] 2019-07-09 13:11
It is disabled by default!

**Comment by JSmythSSG** [comment] 2019-07-09 13:16
> It is disabled by default!

I misread the default, I've set it to HEARTBEAT_INTERVAL = '15s' now and checking the console log

**Comment by JSmythSSG** [comment] 2019-07-09 14:10
So far nothing no SPDY errors with heartbeat of 15s! Thank you, maybe you could add that to known issues for others to try if they keep getting repeated SPDY errors?

**Comment by dunglas** [comment] 2019-07-23 15:33
It would be nice to add it to the troubleshooting section indeed! Can you open a PR?

**Comment by byhoratiss** [comment] 2019-08-13 18:02
Oh, this saved me a lot of time & hair.
Thank you!

**Comment by dunglas** [comment] 2019-08-13 18:56
I think we'll enable the heartbeat mechanism by default instead of adding this to the troubleshooting section.

**Comment by dunglas** [comment] 2020-09-02 10:58
This issue has been fixed in the latest version. Feel free to reopen if it still occurs.

**Closed by dunglas** 2020-09-02 10:58 UTC
Labels: wontfix
