### ISSUE TITLE
Topic selection does not work

### ISSUE THREAD

**Issue by jderusse** [dunglas/mercure#596] opened 2021-12-23 16:12 UTC
Since #578 the topic subscription is ignored.

Reproducer.
- start the Mercure UI
- subscribe to topic `FOO`
- publish in `BAR`
- message is dispatched to subscriber

![Screenshot from 2021-12-23 17-11-15](https://user-images.githubusercontent.com/578547/147266015-252164e8-c1df-46ca-84a3-0147a590f682.png)

/cc @kevburnsjr

**Comment by divine** [comment] 2021-12-24 04:24
Hello,

I wasn't able to reproduce it on a Caddy version.

Probably this is a legacy version that is leaking that data or I'm just blind and somehow missed the last commits?

Thanks!

**Comment by dunglas** [comment] 2021-12-24 07:17
I reproduced and fixed the issue using: https://github.com/dunglas/mercure/pull/597

@divine that's weird, I reproduce the issue with the Caddy build too.

**Comment by divine** [comment] 2021-12-24 07:57
> I reproduced and fixed the issue: #597
> 
> @divine that's weird, I reproduce the issue with the Caddy build too.

Which version does run https://demo.mercure.rocks/ ?

I've tested that on production and nothing is leaking, version build is before this PR was merged https://github.com/dunglas/mercure/pull/563

Interesting...

Thanks!

**Comment by dunglas** [comment] 2021-12-24 08:23
@divine the demo run the on premise (paid) version. Which doesn't include this patch currently.

You can reproduce by cloning the monorepo and starting the Caddy module. You need `github.com/dunglas/mercure@main` (the lib) to reproduce.

**Comment by divine** [comment] 2021-12-26 09:26
Hello,

I've also reproduced this issue locally and actually, it was fun to find the reason why on production it's not leaking, right?

The funny thing is it was installed with the command below and I somehow messed up with dependencies which worked for some reason...

Mercure was built with the command:
`xcaddy build     --with github.com/dunglas/mercure/caddy@99bf84c`

which should be:
`xcaddy build   --with github.com/dunglas/mercure@99bf84c --with github.com/dunglas/mercure/caddy@99bf84c`

I don't think somebody was installing the version from git as it's not released yet... except for a few users maybe...

I hope the fix will be merged soon, maybe I should be installing that version from PR and see if any other issues arise as it's already Christmas!

Merry Christmas!

Thanks!

**Comment by dunglas** [comment] 2021-12-26 10:37
The problem wasn't what I thought initially.
Actually, only the Local transport had been ported to use the new optimized `SubscriberList`, the Bolt transport has been forgotten. I updated the Bolt transport to use the new system in https://github.com/dunglas/mercure/pull/597.

**Comment by divine** [comment] 2021-12-26 10:49
> The problem wasn't what I thought initially. Actually, only the Local transport had been ported to use the new optimized `SubscriberList`, the Bolt transport has been forgotten. I updated the Bolt transport to use the new system in #597.

That makes sense, I've forgotten that we're using local transport and locally we're testing only bolt. Never thought it was a transport problem!

That was fun and thank you for the fix @dunglas!

**Closed** 2021-12-26 14:20 UTC
