### ISSUE TITLE
Mercure Hub not automatically pushing updates

### ISSUE THREAD

**Issue by football2801** [dunglas/mercure#105] opened 2019-06-19 17:44 UTC
I have a quick test Symfony application running to try to integrate the Mercure protocol.

I have a test Mercure hub running with the following:
```bash
JWT_KEY='aVerySecretKey' ADDR='localhost:3000' ALLOW_ANONYMOUS=1 CORS_ALLOWED_ORIGINS=* ./mercure
```

 I have a form that submits the data to the following endpoint:
```php   
     /**
     * @Route("/resources", name="resourcesPost", methods={"POST"})
     */
    public function resourcesPost(Publisher $publisher, Request $request){

        $user = $this->getUser();

        $update = new Update(
            'http://example.com/books/1',
            json_encode([
                'from' => $user->getFullName(),
                'sent at' => (new DateTime())->format('H:i:s'),
                'message' => $request->request->get('message'),
            ])
        );

        $publisher($update);

        return $this->redirectToRoute('resources');
    }
```
Once I hit the form I get the following in the debugger:
```bash
127.0.0.1 - - [19/Jun/2019:13:27:40 -0400] "GET /hub?topic=http%3A%2F%2Fexample.com%2Fbooks%2F1&topic=http%3A%2F%2Fexample.com%2Fbooks%2F2&topic=http%3A%2F%2Fexample.com%2Freviews%2F%7Bid%7D HTTP/1.1" 200 31 "http://localhost:8888/resources" "Mozilla/5.0 (Windows N
T 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0"
time="2019-06-19T13:32:50-04:00" level=info msg="Subscriber disconnected" remote_addr="127.0.0.1:65391"
time="2019-06-19T13:32:53-04:00" level=info msg="Update published" event_id=cd3acff1-7e9b-4e28-b6ba-e79aeb4c1791 remote_addr="127.0.0.1:49546"
127.0.0.1 - - [19/Jun/2019:13:32:53 -0400] "POST /hub HTTP/1.0" 200 36 "" ""
time="2019-06-19T13:32:53-04:00" level=info msg="Event sent" event_id=cd3acff1-7e9b-4e28-b6ba-e79aeb4c1791 remote_addr="127.0.0.1:65384"
```
However, the javascript on the second browser that is listening, does not put the response in the console log :

```javascript
  const u = new URL('http://localhost:3000/hub');
  u.searchParams.append('topic', 'http://example.com/books/1');
  // Subscribe to updates of several Book resources
  u.searchParams.append('topic', 'http://example.com/books/2');
  // All Review resources will match this pattern
  u.searchParams.append('topic', 'http://example.com/reviews/{id}');
   
  const es = new EventSource(u);
  let lastEventId = null;
  es.onmessage = e => {
       let data = JSON.parse(e.data);
       lastEventId = e.lastEventId;
       console.log(data);
  }
```
If I go into the back into the terminal and run `ctrl+c` (to kill the Mercure server) the data will then get pushed into the javascript. My question is how do I get it to automatically push the data to the javascript without having to kill the Mercure server (running on localhost:3000) and then restart it?

**Comment by dunglas** [comment] 2019-06-19 20:23
It's super weird. What OS do you use?

**Comment by football2801** [comment] 2019-06-19 20:52
Windows 10 running the client in a Git Bash environment

**Comment by football2801** [comment] 2019-06-20 13:54
I just ran some more tests in my windows 10 environment.
If I build a batch file that was recommended in issue #76 and run it in Command Prompt, I get the exact same functionality as I get from Git Bash. Same with Windows PowerShell. I have to close the server connection for the clients to receive the data.

**Comment by dunglas** [comment] 2019-06-20 21:05
I'm tested on Mac on Linux and isn't able to reproduce. Unfortunately I don't have a Windows computer available right now. I'll try to get one and to test next week.

**Comment by txptr** [comment] 2019-06-27 09:08
Same problem here. Windows 10 with PowerShell running the mercure Server.

In Chrome Dev Tools the connection to "hub?topic=..." is marked as pending and I have no "EventStream" tab under the connection details. After shutting down the mercure server, the "EventStream" tab is visible and the script tries to reconnect to the hub.

**Comment by txptr** [comment] 2019-06-27 09:36
I found the solution for me and maybe you:

I've set the wrong value for the env variable --> ADDR="127.0.0.1:3000"
After setting it to ADDR=":3000" everything workes fine and windows asked me for giving "mercure.exe" firewall access. Hope this helps @football2801

**Comment by football2801** [comment] 2019-06-27 15:00
@txptr I owe you a drink! This has me so much closer. I'm still having some issues, but chrome is accepting the response from the hub instantly. 
Unfortunately firefox, IE, and Edge are both ignoring the event's from the hub still.

**Comment by football2801** [comment] 2019-06-27 15:01
Can somebody give detailed instructions on how to deploy this to a CENTOS7 linux server? I'll give up on the local development environment and push to a linode, but I am completely unsure how to do so.

**Comment by mantis** [comment] 2019-07-06 17:24
@dunglas i'm also getting same behaviour as @football2801. Chrome works, Firefox only updates when Ctrl+C the mercure service

**Comment by falconsmilie** [comment] 2019-07-28 05:52
@dunglas Same issue here. 

Event is not received until i Ctrl+C the Mercure server in Git bash. 

Running Windows 10 with Mercure allowed in Windows Firewall. 

Laravel to serve the subscriber page using; `idplus/laravel-mercure-publisher` and `php artisan server`. 

Calling the subscriber through Chrome; `http://127.0.0.1:8000/subscribe`

Using curl (or new browser tab) to call the publisher; `curl http://127.0.0.1:8000/publish`

Running Mercure with;
` JWT_KEY='realBadKey' ADDR=':3000' DEMO=1 ALLOW_ANONYMOUS=1 CORS_ALLOWED_ORIGINS=* PUBLISH_ALLOWED_ORIGINS='http://localhost:3000' ./mercure`

Here is the log;

`$ JWT_KEY='realBadKey' ADDR=':3000' DEMO=1 ALLOW_ANONYMOUS=1 CORS_ALLOWED_ORIGINS=* PUBLISH_ALLOWED_ORIGINS='http://localhost:3000' ./mercure
time="2019-07-28T07:45:20+02:00" level=info msg="Mercure started" protocol=http
time="2019-07-28T07:45:21+02:00" level=info msg="New subscriber" remote_addr="127.0.0.1:58542"
127.0.0.1 - - [28/Jul/2019:07:45:21 +0200] "GET /hub?topic=mytopicname HTTP/1.1" 200 31 "http://127.0.0.1:8000/subscribe" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36"
time="2019-07-28T07:45:34+02:00" level=info msg="Subscriber disconnected" remote_addr="127.0.0.1:58542"
time="2019-07-28T07:45:34+02:00" level=info msg="New subscriber" remote_addr="127.0.0.1:58548"
time="2019-07-28T07:45:41+02:00" level=info msg="Update published" event_id=fa86a1a6-65ef-41d6-8d3f-bd4ee9f9320d remote_addr="127.0.0.1:58552"
127.0.0.1 - - [28/Jul/2019:07:45:41 +0200] "POST /hub HTTP/1.0" 200 36 "" ""
time="2019-07-28T07:45:41+02:00" level=info msg="Event sent" event_id=fa86a1a6-65ef-41d6-8d3f-bd4ee9f9320d remote_addr="127.0.0.1:58548"

// This gap here is where i press Ctrl + C, then the following happens;

127.0.0.1 - - [28/Jul/2019:07:45:34 +0200] "GET /hub?topic=mytopicname HTTP/1.1" 200 108 "http://127.0.0.1:8000/subscribe" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36"
time="2019-07-28T07:45:58+02:00" level=info msg="My Baby Shot Me Down"
`

**Comment by dunglas** [comment] 2019-07-29 06:17
Honestly, I've no clue of what's going on. I'm abroad for some weeks, but when I'll be back at the office I'll try to find a Windows computed to debug this. Any more information you can gather will be very appreciated.

In the meantime, maybe can you use Docker or any other Unix-based solution (a VM, Vagrant, Laravel Homestead etc) to run the Mercure hub?

**Comment by mantis** [comment] 2019-08-10 19:23
@falconsmilie @dunglas  - I spent a while looking at this today

I *think* that the issue here seems to be that the solution only works with HTTP/2. 

In my initial setup, I was using localhost - I then tried on a linux server remotely with HTTP (not https) and Compress = 0. My initial thoughts was whether it was the linefeeds being generated. The sendheader's routine adds a dummy :\n message to push the headers out from GO, however I believe the protocol normally expects to see \n\n ?

In any case, with HTTP - I was finding that chrome/firefox etc do not work either locally or remotely.

I've then used the command line to generate a dummy openssl certificate

> openssl req -newkey rsa:2048 -nodes -keyout domain.key -x509 -days 365 -out domain.crt

And specifieid this as extra paramater to the mercure application: 

>  "CERT_FILE": "domain.crt", "KEY_FILE": "domain.key"

At first glance, the browsers now seem to be processing the responses correctly.

In terms of debugging this:

1) onopen hook

If adding a onopen hook to the javascript e.g.:

``
es.onopen = e => {
 console.log("open");
}
``

The word 'open' does not appear in the console until pressing ctrl+c in mercure.

2) tcp dump -wireshark with npcap for localhost debugging

A wireshark trace showed the mercure client sending the message to the mercure server and the mercure server sending the message to the browser. 

Until Ctrl+C is pressed in mercure, nothing is processed. 

I was hitting the same issue with responses not being processed when trying some online sample code for SSE (e.g. https://github.com/mchaov/simple-sse-nodejs-setup ) - so I'm not sure if the browser vendors have changed something such that https is required or similar for this to work.

**Comment by noubicastel4** [comment] 2019-09-06 18:42
Hello I have a problem to subscribe. When i pubish throuth mercure server after subscribing i get the data respone in my console but when i subscribe after publishing, i don't have anything as response. Please can i have a solution for it ?

Please excuse me for my bad english.

**Comment by football2801** [comment] 2019-09-20 21:23
Any progress? We are at a point in my project where we either need to get this running or switch to another service.

**Comment by mantis** [comment] 2019-09-20 21:25
@football2801 did you move from local development ?

**Comment by football2801** [comment] 2019-09-20 22:10
We are attempting to deploy and test on a Linux machine running CentOS. We have so far been unable to get our localhost project to connect to the server to test. Typically getting 401 errors. We have yet to get it to connect as of right now.

**Comment by mantis** [comment] 2019-09-20 22:49
when I tried to debug this - i came to conclusion that it might be better to try non-localhost

**Comment by football2801** [comment] 2019-09-24 20:42
We have the code now running and posting to the CentOS machine. We get the Event Sent notification after POSTing to the server, but the server does not actually send the response through until I ctrl-c the connection.

**Comment by dunglas** [comment] 2019-09-24 21:04
Is there some kind of firewall on CentOS?

**Comment by dunglas** [comment] 2019-09-24 21:14
Could you try to add a breakpoint here to see if it's called or not? https://github.com/dunglas/mercure/blob/master/hub/subscribe.go#L186

**Comment by dunglas** [comment] 2019-09-24 21:19
On Windows, you should disable any firewall, antivirus, and check for malwares. It's most likely the cause of the issue.

**Comment by football2801** [comment] 2019-09-25 13:30
I can't debug that line, I don't have the ability to add breakpoints on the Linux server. The CentOS machine is a remote server hosted by Linode. We have set it up with a temporary URL to be able to POST traffic from localhost to an actual remote environment to best simulate what the production environment will be.

The command we are running in Linux is:
`JWT_KEY='!ChangeMe!' ADDR=':3000' ALLOW_ANONYMOUS=1 CORS_ALLOWED_ORIGINS=* ./mercure`

**Comment by football2801** [comment] 2019-09-25 18:31
> On Windows, you should disable any firewall, antivirus, and check for malwares. It's most likely the cause of the issue.

This seems to be the issue. I have the exact same code running on a mac and everything works in all browsers that I've tested. 

The major issue remains that I work in a large corporation who wants to use this software, we have managed firewalls and antivirus on our machines. If we want to use this service, we need to know what to allow through the security. So far we've tried a few things such as the CentOS server's ip, but the browser on windows still reports that it cannot make a connection.

The CentOS machine shows the event subscription, but the browser says that it cannot connect, almost as if the handshake is being made on the server, but the response is not making it back to the local machine.

**Closed** 2019-10-05 12:22 UTC
Labels: Hacktoberfest, ⭐️ EUFOSSA Hackathon

**Comment by stinndler** [comment] 2020-01-29 22:15
I'm having a similar issue when accessing from outside my firewall. If i'm at home on the same network then this all works as expected. However if I'm outside I get the never ending "pending" on the connection until I ctrl+c the mercure server then the streams come through. 

My firewall already has port 3000 open. Is there anything else I'm missing here? 
this is my server string:
./mercure --jwt-key='mybadkey' --addr=':3000' --debug --allow-anonymous --cors-allowed-origins='*' --publish-allowed-origins='http://myexternal.name.com:3000'

Like I said when I'm home it works perfectly so it has to be something on the firewall. The server is running on linux. I'm at a loss.
