### ISSUE TITLE
Issue Handling Requests Larger Than 10 MB

### ISSUE THREAD

**Issue by emil-1996** [dunglas/mercure#927] opened 2024-07-31 21:16 UTC
Description:
When attempting to send a request larger than 10 MB to Mercure, I consistently receive an HTTP/1.1 400 Bad Request error. The request in question is targeting the URL http://mercure:8443/.well-known/mercure.

Details:
The Content-Length header indicates a body size of 16,235,362 bytes.
However, the bytes_read logs show only 10,485,761 bytes being processed before the request fails.

Question:
How can I configure Mercure to accept request bodies larger than 10 MB?

**Comment by emil-1996** [comment] 2024-07-31 22:02
It seems this issue is related to [#878](https://github.com/dunglas/mercure/issues/878).

While I understand that reducing the message size can be a workaround, I believe that the application should not, by default, limit the size of the request a user can make. Perhaps introducing a configurable flag, such as a max request size, might be a more flexible solution.

**Comment by dunglas** [comment] 2024-08-01 06:38
This is a Go limitation. Currently it's not possible to bypass it.

**Comment by dunglas** [comment] 2024-08-01 06:38
Closing as duplicate of #878.

**Closed** 2024-08-01 06:39 UTC
